---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'starter'

StringField:
  extensions:
    - StringFormatter

SiteConfig:
  emails:
    adminEmail: 'blair@pacificjemm.com'
    testEmail: 'hello@swordfox.nz'
    bccEmail: 'alerts@swordfox.nz'
    sendGridKey: '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' # Small Projects
