---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'forum/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'starter'

StringField:
  extensions:
    - StringFormatter

EventApi:
  eventFinderUsername: lakesleisure2
  eventFinderPassword: 6fc7wyf6n5qm
  eventEndPoint: http://api.eventfinder.co.nz/v2/events.json
  categoryEndPoint: http://api.eventfinder.co.nz/v2/categories.json
  locationEndPoint: